<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE reyesEspanoles [
    <!ELEMENT reyesEspanoles (rey | reina)*>
    <!ELEMENT rey (nombre, padre, madre)>
    <!ELEMENT reina (nombre, padre, madre)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT padre (#PCDATA)>
    <!ELEMENT madre (#PCDATA)>
]>

<reyesEspanoles>
    <rey>
        <nombre>Felipe III</nombre>
        <padre>Felipe II</padre>
        <madre>Ana de Austria</madre>
    </rey>
    <reina>
        <nombre>Juana "La Loca"</nombre>
        <padre>Fernado "El Católico"</padre>
        <madre>Isabel "La Católica"</madre>
    </reina>
    <rey>
        <nombre>Carlos I</nombre>
        <padre>Felipe "El Hermoso"</padre>
        <madre>Juan "La Loca"</madre>
    </rey>
</reyesEspanoles>
