<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ejemplo [

  <!ELEMENT  pagina (cualquier_contenido)>
  <!ELEMENT cualquier_contenido ANY>
  <!ELEMENT texto (#PCDATA)>
]>

<ejemplo>
    <cualquier_contenido>
        <texto>Texto</texto>
        <texto>Texto</texto>
        <texto>Texto</texto>
    </cualquier_contenido>
</ejemplo>