<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE articulo [
    <!ELEMENT articulo (codigo, id)*>
    <!ELEMENT codigo (#PCDATA)>
    <!ELEMENT id (#PCDATA)>
]>

<articulo>
    <codigo>C001-A</codigo>
    <id>3000094</id>
    <codigo>C001-B</codigo>
    <codigo>C001-C</codigo>
</articulo>