<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cine [
    <!ELEMENT cine (directores, peliculas)>
    <!ELEMENT directores (director)*>
    <!ELEMENT director (#PCDATA)>
        <!ATTLIST director coddir ID #REQUIRED>
    <!ELEMENT peliculas (pelicula)*>
    <!ELEMENT pelicula (#PCDATA)>
        <!ATTLIST pelicula direccion IDREF #REQUIRED>
]>
<cine>
    <directores>
        <director coddir="CE">Clint EastWood</director>
        <director coddir="JC">James Cameron</director>
    </directores>
    <peliculas>
        <pelicula direccion="JC">Avatar</pelicula>
        <pelicula direccion="CE">Million Dollar Baby</pelicula>
        <pelicula direccion="JC">Titanic</pelicula>
    </peliculas>
</cine>